export const stagedata = {
  StageTotal: 2,
  data: [
    {
      Stage: 1,
      StageName: 'フワマ平原',
      StageId: 'huwama',
      info: {
        1: {
          StageId: 1,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        2: {
          StageId: 2,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        3: {
          StageId: 3,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        4: {
          StageId: 4,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        5: {
          StageId: 5,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        6: {
          StageId: 6,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        7: {
          StageId: 7,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        8: {
          StageId: 8,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        9: {
          StageId: 9,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
        10: {
          StageId: 10,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
      },
    },
    {
      Stage: 1,
      StageName: 'ヤルシヤオ高原',
      StageId: 'yarusiyao',
      info: {
        1: {
          StageId: 1,
          EnemyName: 'スライム',
          EnemyHp: 7,
          EnemyAtk: 1,
          EnemyDef: 1,
          EnemySpd: 1,
          ExpMin: 1,
          ExpMax: 3,
          CoinMin: 1,
          CoinMax: 1,
        },
      },
    },
  ],
}
export const item = {
  item: {
    0: { name: 'デバッグ用', buy: 0, sell: 0 },
    1: { name: 'テストアイテム', buy: 5, sell: 2 },
    2: { name: 'test', buy: 4, sell: 2 },
  },
  weapon: {},
  other: {},
}
